name: flutter_chat_ui
description: >
  Actively maintained, community-driven chat UI implementation with an
  optional Firebase BaaS.
version: 1.6.6
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  diffutil_dart: ^3.0.0
  bubble: ^1.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_link_previewer: ^3.2.0
  flutter_parsed_text: ^2.2.1
  intl: ^0.18.0
  meta: ^1.9.1
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.6
  visibility_detector: ^0.3.3
  swipeable_tile: ^1.0.0+6
  flutter_sound: ^9.2.13
  path_provider: ^2.0.5
  uuid: ^3.0.7
  path: ^1.8.0
  video_player: ^2.2.5
  camera: ^0.10.4
  shared_preferences: ^2.1.0
  audio_session: ^0.1.18

dev_dependencies:
  dart_code_metrics: ^4.21.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_chat_types:
    # path: ./flutter_chat_types
    git:
      url: https://github.com/marctan/flutter_chat_types.git

flutter:
  assets:
    - packages/flutter_chat_ui/assets/icon-arrow.png
    - packages/flutter_chat_ui/assets/icon-attachment.png
    - packages/flutter_chat_ui/assets/icon-delivered-2.png
    - packages/flutter_chat_ui/assets/icon-delivered.png
    - packages/flutter_chat_ui/assets/icon-document.png
    - packages/flutter_chat_ui/assets/icon-error.png
    - packages/flutter_chat_ui/assets/icon-reply.png
    - packages/flutter_chat_ui/assets/icon-seen.png
    - packages/flutter_chat_ui/assets/icon-seen-2.png
    - packages/flutter_chat_ui/assets/icon-send.png
    - packages/flutter_chat_ui/assets/2.0x/icon-arrow.png
    - packages/flutter_chat_ui/assets/icon-x.png
    - packages/flutter_chat_ui/assets/2.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/2.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/2.0x/icon-delivered-2.png
    - packages/flutter_chat_ui/assets/2.0x/icon-document.png
    - packages/flutter_chat_ui/assets/2.0x/icon-error.png
    - packages/flutter_chat_ui/assets/2.0x/icon-reply.png
    - packages/flutter_chat_ui/assets/2.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/2.0x/icon-send.png
    - packages/flutter_chat_ui/assets/2.0x/icon-seen-2.png
    - packages/flutter_chat_ui/assets/3.0x/icon-arrow.png
    - packages/flutter_chat_ui/assets/2.0x/icon-x.png
    - packages/flutter_chat_ui/assets/3.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/3.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/3.0x/icon-delivered-2.png
    - packages/flutter_chat_ui/assets/3.0x/icon-document.png
    - packages/flutter_chat_ui/assets/3.0x/icon-error.png
    - packages/flutter_chat_ui/assets/3.0x/icon-reply.png
    - packages/flutter_chat_ui/assets/3.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/3.0x/icon-send.png
    - packages/flutter_chat_ui/assets/3.0x/icon-x.png
    - packages/flutter_chat_ui/assets/3.0x/icon-seen-2.png

  fonts:
    - family: Helvetica
      fonts:
        - asset: lib/assets/fonts/Helvetica.ttf
        - asset: lib/assets/fonts/Helvetica-Bold.ttf
        - asset: lib/assets/fonts/Helvetica-BoldOblique.ttf
          
